var Codec2Module=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var b=moduleArg,f="",g;try{f=(new URL(".",_scriptName)).href}catch{}g=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var h=console.error.bind(console),k,l=!1,m,n,p,q=!1;function r(a){b.onAbort?.(a);a=`Aborted(${a})`;h(a);l=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p?.(a);throw a;}var t;
async function u(a){if(!k)try{var d=await g(a);return new Uint8Array(d)}catch{}if(a==t&&k)a=new Uint8Array(k);else throw"both async and sync fetching of the wasm failed";return a}async function v(a,d){try{var c=await u(a);return await WebAssembly.instantiate(c,d)}catch(e){h(`failed to asynchronously prepare wasm: ${e}`),r(e)}}
async function w(a){var d=t;if(!k)try{var c=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){h(`wasm streaming compile failed: ${e}`),h("falling back to ArrayBuffer instantiation")}return v(d,a)}class x{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var y=a=>{for(;0<a.length;)a.shift()(b)},z=[],A=[],B=()=>{var a=b.preRun.shift();A.push(a)},C=!0,D=0,E={},F=a=>{if(!(a instanceof x||"unwind"==a))throw a;},G=a=>{m=a;C||0<D||(b.onExit?.(a),l=!0);throw new x(a);},H=a=>{if(!l)try{a()}catch(d){F(d)}finally{if(!(C||0<D))try{m=a=m,G(a)}catch(d){F(d)}}};b.noExitRuntime&&(C=b.noExitRuntime);b.printErr&&(h=b.printErr);b.wasmBinary&&(k=b.wasmBinary);if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();
var I,J,K={c:()=>r(""),b:()=>{C=!1;D=0},d:(a,d)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!d)return 0;var c=setTimeout(()=>{delete E[a];H(()=>I(a,performance.now()))},d);E[a]={id:c,l:d};return 0},a:G},L;
L=await (async function(){function a(c){c=L=c.exports;b._malloc=c.g;b._free=c.h;b._decode_to_wav=c.i;I=c.j;J=c.e;c=J.buffer;new Int8Array(c);new Int16Array(c);b.HEAPU8=new Uint8Array(c);new Uint16Array(c);new Int32Array(c);new Uint32Array(c);new Float32Array(c);new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c);return L}var d={a:K};if(b.instantiateWasm)return new Promise(c=>{b.instantiateWasm(d,(e,M)=>{c(a(e,M))})});t??=b.locateFile?b.locateFile("codec2.wasm",f):f+"codec2.wasm";
return a((await w(d)).instance)}());(function(){function a(){b.calledRun=!0;if(!l){q=!0;L.f();n?.(b);b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var d=b.postRun.shift();z.push(d)}y(z)}}if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)B();y(A);b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()})();
q?moduleRtn=b:moduleRtn=new Promise((a,d)=>{n=a;p=d});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Codec2Module;module.exports.default=Codec2Module}else if(typeof define==="function"&&define["amd"])define([],()=>Codec2Module);
